To get groups claim for Group Overage scenario for Web API
Azure-Samples/ms-identity-javascript-angular-spa-dotnetcore-webapi-roles-groups pull request #3
Opened 2020-08-04 16:28 UTC by Shama-K

Updated Web API code to get all the groups in case of groups overage.

2020-08-04 17:05 UTC, derisen reviewed
Works like a charm, thanks Shama! Could you also update the readme as well, adding instructions about 'client secret' and 'offline_access' scopes to the api registration part? Also updating the 'About the Code' section / api part would be great.

2020-08-05 20:46 UTC, derisen approved these changes
LGTM!

2020-08-18 17:41 UTC, derisen approved these changes
Just installed and tested again. LGTM!

2020-08-26 23:20 UTC, idg-sam commented
Looks good to me!
1. Should we grant admin consent in the instructions?
2. We should change existing manual steps for groups emission to tell user exactly how to add it in IDT and AT
3. New manual step should also be added for modifying app-config.json to add group IDs of GroupAdmin and GroupMember to SPA
4. 3. New manual step should also be added for modifying appsettings.json to add group IDs of GroupAdmin and GroupMember to API

2020-08-26 23:51 UTC, idg-sam requested changes
Looks good to me!

- Should grant admin consent in the instructions
- In script-based configuration:
   - ~~We should change additional manual stepsfor groups emission to tell user exactly how to add it in IDT and AT~~ Remove the manual step for group claim emission in IDT and AT, since it is already in place 
   - New manual step should also be added for modifying app-config.json to add group IDs of GroupAdmin and GroupMember to SPA
   - New manual step should also be added for modifying appsettings.json to add group IDs of GroupAdmin and GroupMember to API

2020-08-27 16:27 UTC, TiagoBrenck approved these changes
I am approving, but with the same observations as Sam

2020-09-22 21:33 UTC, Shama-K commented
> Looks good to me!
> 
> * Should grant admin consent in the instructions
> * In script-based configuration:
>   
>   * ~We should change additional manual stepsfor groups emission to tell user exactly how to add it in IDT and AT~ Remove the manual step for group claim emission in IDT and AT, since it is already in place
>   * New manual step should also be added for modifying app-config.json to add group IDs of GroupAdmin and GroupMember to SPA
>   * New manual step should also be added for modifying appsettings.json to add group IDs of GroupAdmin and GroupMember to API

Addressed the suggestions.

2020-09-24 07:31 UTC, kalyankrishna1 approved these changes
:shipit:

2020-09-24 07:34 UTC, kalyankrishna1 commented on chapter2/README.md
> +                private static async Task ProcessUserGroupsForOverage(TokenValidatedContext context)
>ProcessUserGroupsForOverage [](start = 42, length = 27)

you dont have to print the whole method

2020-09-24 16:34 UTC, Shama-K commented on chapter2/README.md
> +                private static async Task ProcessUserGroupsForOverage(TokenValidatedContext context)
Updated the Readme files.
Thanks.

2020-09-24 19:34 UTC, derisen approved these changes
Great work Shama, thanks. Just make sure to pull in the latest changes to master before merging.

2020-09-24 21:21 UTC, merged